/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4 at Sun Jan 31 15:30:20 2016. */

#ifndef PB_HEADER_PB_H_INCLUDED
#define PB_HEADER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Header {
    bool has_arduinoId;
    char arduinoId[20];
    bool has_sensorId;
    char sensorId[20];
} Header;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Header_init_default                      {false, "", false, ""}
#define Header_init_zero                         {false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Header_arduinoId_tag                     1
#define Header_sensorId_tag                      2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Header_fields[3];

/* Maximum encoded size of messages (where known) */
#define Header_size                              44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HEADER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
