/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Sun Jan 31 15:30:20 2016. */

#include "header.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Header_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, Header, arduinoId, arduinoId, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, Header, sensorId, arduinoId, 0),
    PB_LAST_FIELD
};


